# 產生陣列

In [28]:
import numpy as np

In [29]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [2]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [3]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.linspace(0,1,11) #產生等差數列

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [9]:
np.linspace(0,10,11) #產生等差數列

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
np.logspace(0,100,10) #產生對數數列

array([1.00000000e+000, 1.29154967e+011, 1.66810054e+022, 2.15443469e+033,
       2.78255940e+044, 3.59381366e+055, 4.64158883e+066, 5.99484250e+077,
       7.74263683e+088, 1.00000000e+100])

In [16]:
np.zeros((3,3)) #全為0的二維陣列

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [19]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [18]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [23]:
np.identity((3))  #產生單位矩陣

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 陣列運算 

In [32]:
x = np.array((1,2,3,4,5))

In [33]:
x

array([1, 2, 3, 4, 5])

In [34]:
x*2

array([ 2,  4,  6,  8, 10])

In [35]:
x/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [36]:
x//2

array([0, 1, 1, 2, 2], dtype=int32)

In [37]:
x**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [38]:
x+2

array([3, 4, 5, 6, 7])

In [40]:
x%3

array([1, 2, 0, 1, 2], dtype=int32)

In [41]:
a = np.array((1,2,3))

In [43]:
b = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [44]:
a

array([1, 2, 3])

In [45]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
c = a*b
c

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [49]:
c/b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [50]:
a+a

array([2, 4, 6])

In [51]:
a*a

array([1, 4, 9])

In [52]:
a-a

array([0, 0, 0])

In [53]:
a/a

array([1., 1., 1.])

# 二維轉置

In [55]:
b = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [56]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
b.T  #轉置

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [60]:
a = np.array((1,2,3,4))

In [62]:
a.T #一維陣列轉置 還是和原來一樣

array([1, 2, 3, 4])

# 向量積

In [63]:
a = np.array([5,6,7])

In [64]:
b = np.array([6,6,6])

In [65]:
a.dot(b)

108

In [66]:
c = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [67]:
cT = c.T

In [68]:
c.dot(a)

array([ 38,  92, 146])

In [69]:
cT.dot(a)

array([ 78,  96, 114])

In [70]:
c[0].dot(a)

38

In [71]:
a.dot(cT[1])

96

# 存取陣列元素

In [72]:
c = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [73]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
c[0]

array([1, 2, 3])

In [75]:
c[0,0]

1

In [79]:
x = np.arange(0,100,10,dtype=np.floating)

In [80]:
x

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [83]:
index = np.random.randint(0,len(x),5)  #隨機產生5個亂數

In [84]:
index

array([8, 1, 0, 6, 2])

In [85]:
x[index]

array([80., 10.,  0., 60., 20.])

In [88]:
x[index] = [1,2,3,4,5]

In [89]:
x

array([ 3.,  2.,  5., 30., 40., 50.,  4., 70.,  1., 90.])

In [90]:
x[[1,2,3]]

array([ 2.,  5., 30.])

In [91]:
np.sin(x)

array([ 0.14112001,  0.90929743, -0.95892427, -0.98803162,  0.74511316,
       -0.26237485, -0.7568025 ,  0.77389068,  0.84147098,  0.89399666])

In [94]:
np.round(_)

array([ 0.,  1., -1., -1.,  1., -0., -1.,  1.,  1.,  1.])

In [95]:
x = np.random.rand(10)*10
x

array([8.97564185, 7.8757471 , 6.38171158, 8.6281985 , 5.29222652,
       2.13263198, 8.6568404 , 6.85652264, 4.69957721, 3.82722498])

In [98]:
np.floor(x) #取地板整數

array([8., 7., 6., 8., 5., 2., 8., 6., 4., 3.])

In [100]:
np.ceil(x) #取天花板整數

array([9., 8., 7., 9., 6., 3., 9., 7., 5., 4.])

In [106]:
x = np.arange(0,10).reshape(2,5)

In [107]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])